### PR TITLE
Refactor NuGet packaging to support .NET Framework

### PR DESCRIPTION
**Pull request by Achilles1515**
This PR refactors the NuGet packaging and HDF5 DLL loading to properly support all .NET Core and .NET Framework project and package reference styles.

The .targets file is moved under the HDF.PInvoke.1.10 project and added to the NuGet package as a build target for .NET Framework only, and includes updated conditionals for appropriately copying the HDF5 binaries while keeping support for AnyCPU build configurations. The HDF5 binaries are copied similar to a .NET Core configuration.

In short, an AnyCPU (64-bit preferred) build will output `runtime\win-x{PlatformTarget}\native\` directories and every other configuration will place the appropriate platform target binaries directly in the build output folder.

This .targets file also includes a fix for [this stupid RuntimeIdentifier bug](https://github.com/dotnet/sdk/issues/1545) that Microsoft refuses to fix, and it will output a build message if it does encounter and fix the problem.

Adding this .targets file to the `\build` and `\buildTransitive` package paths gives support to non-SDK style project files as well as those using `packages.config` instead of `PackageReference`.

Also, the previous .targets file had a bug due to a property name typo:
`<Is64BitProcess Condition="$(TargetPlatform) != 'x86'">True</Is64BitProcess>`

`TargetPlatform` should be `PlatformTarget` --> this was causing `Is64BitProcess` to always be true.

Though, the binary copying be done in the previous .targets file is only applicable to the UnitTests project and was moved into its .csproj file.

### CODE REVIEW

**Comment by Apollo3zehn** [comment]
Thanks 👍  I will check this as soon as possible. But before the CI build should work. Do you know what went wrong?

**Comment by Achilles1515** [comment]
Travis is showing this error:
```
Error: Unknown command: cask
The command "brew cask install powershell" failed and exited with 1 during .
```

I have no idea what that's about.

I fixed the AppVeyor failure - I had never dealt with an empty `PlatformTarget` property before (thought it was always assigned something...), but I added an additional check for it to produce a similar output for the `Is64BitProcess` as was done prior.

**Comment by Apollo3zehn** [comment]
I had to change the .targets file a little bit because I found a few configurations where the dll's were not found. I have tested it now on my x64 PC with the following project/nuget combinations:

- netfx + old csproj style + packages config
- netfx + old csproj style + package reference
- netfx + new csproj style + package reference
- corefx

And with the following platform targets:
- AnyCPU, without prefer 32 bit
- AnyCPU, with prefer 32 bit
- x86
- x64

All of them worked for me.

I could not test it on a x86 machine because I do not have one available.

The test setup is attached:
[hdf_pinvoke_tests.zip](https://github.com/HDFGroup/HDF.PInvoke.1.10/files/6196656/hdf_pinvoke_tests.zip)

Do you think my changes are OK? Do you see any problems?

**Comment by Achilles1515** [comment]
@Apollo3zehn Thanks for reviewing.
Questions regarding your changes:

What is the purpose of adding the `MSBuildRuntimeType` checks? I've never used this property, but it basically appears like the value won't be `Full` when using `dotnet build` - but this command requires an SDK style project and we were already checking for the `UsingMicrosoftNETSdk` property.

It also looks like you removed any chance of the native runtimes being placed in the `runtimes\win-....` folders, which could make the app try to load the wrong architecture dll.
For example, if I open up your **netfx_oldstyle_packages_config** project and build with configuration AnyCPU (64-bit preferred),  then the 64-bit `hdf5.dll` and `hdf5_hl.dll` libraries are copied directly into the build output and the 32-bit versions are nowhere to be seen. This runs fine on a 64-bit machine but will throw a `BadImageFormatException` on a 32-bit machine. Since this is an AnyCPU build, we should be able to copy the build output folder directly to a 32-bit machine and run the program successfully. This is why, for this configuration, I was copying both the 32-bit and 64-bit dlls into their respective `runtime\win-...` folder because we don't know for sure what architecture the app will be running under.

(And since we are talking about .NET Framework, the `runtime\win-x86(or x64)` folder is technically just an arbitrary name and could be `bin32` or `bin64` like the other HDF.PInvoke project, but I chose to mimic the folder structure that could be output for .NET Core builds for consistency sake)

> ... I found a few configurations where the dll's were not found.

Can you recall which one(s) weren't working for you?

> I could not test it on a x86 machine because I do not have one available.

Same.

**Comment by Apollo3zehn** [comment]
The purpose of the `MSBuildRuntimeType` checks is to distinguish between .NET Core and .NET Framework. The .targets file is not required on .NET Core. I also have noticed that `dotnet xxx` commands do not work as expected so I agree, another way to exclude .NET Core is required.

You are right, I removed the `runtimes` folder structure. I did this because the DLLs were not loaded when I tried to run the app. However, I think I got the AnyCPU idea wrong. Sorry for the confusion, I`ll check that targets file again.

**Comment by Achilles1515** [comment]
> The purpose of the `MSBuildRuntimeType` checks is to distinguish between .NET Core and .NET Framework. The .targets file is not required on .NET Core. I also have noticed that `dotnet xxx` commands do not work as expected so I agree, another way to exclude .NET Core is required.

The targets file will already not be ran at all for .NET Core because the `PackagePath` within the NuGet is specific to .NET Framework (`net461` i.e. .NET Framework 4.6.1+)

```xml
<Content Include="HDF.PInvoke.1.10.targets">
      <PackagePath>build/net461;buildTransitive/net461</PackagePath>
</Content>
```

**Comment by Apollo3zehn** [comment]
My fault was to create a test like `HDF.PInvoke.H5.open();` which does not invoke the static DLL loader constructor which in turn causes some tests to fail. I understand now. I´ll test again once with your original version and when everything is fine I`ll merge it. Thanks for your work!

**Pull request merged**
